// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/greet/[name].tsx";
import * as $4 from "./routes/greet/index copy.tsx";
import * as $5 from "./routes/import_trades.tsx";
import * as $6 from "./routes/index.tsx";
import * as $7 from "./routes/index_original.tsx";
import * as $8 from "./routes/notebook.tsx";
import * as $9 from "./routes/stats_daily.tsx";
import * as $10 from "./routes/trade/[tradeID].tsx";
import * as $11 from "./routes/trade_log.tsx";
import * as $12 from "./routes/trades.tsx";
import * as $$0 from "./islands/Countdown.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/SideMenu.tsx";
import * as $$3 from "./islands/TradeLogTable.tsx";
import * as $$4 from "./islands/chart.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/greet/[name].tsx": $3,
    "./routes/greet/index copy.tsx": $4,
    "./routes/import_trades.tsx": $5,
    "./routes/index.tsx": $6,
    "./routes/index_original.tsx": $7,
    "./routes/notebook.tsx": $8,
    "./routes/stats_daily.tsx": $9,
    "./routes/trade/[tradeID].tsx": $10,
    "./routes/trade_log.tsx": $11,
    "./routes/trades.tsx": $12,
  },
  islands: {
    "./islands/Countdown.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/SideMenu.tsx": $$2,
    "./islands/TradeLogTable.tsx": $$3,
    "./islands/chart.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
