// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/ai-coach.ts";
import * as $3 from "./routes/api/export.ts";
import * as $4 from "./routes/api/import-backup.ts";
import * as $5 from "./routes/api/klines.ts";
import * as $6 from "./routes/api/trades.ts";
import * as $7 from "./routes/import_trades.tsx";
import * as $8 from "./routes/index.tsx";
import * as $9 from "./routes/notebook.tsx";
import * as $10 from "./routes/playbook.tsx";
import * as $11 from "./routes/settings.tsx";
import * as $12 from "./routes/stats_daily.tsx";
import * as $13 from "./routes/trade/[tradeID].tsx";
import * as $14 from "./routes/trade_log.tsx";
import * as $$0 from "./islands/AICoachButton.tsx";
import * as $$1 from "./islands/AddTradeForm.tsx";
import * as $$2 from "./islands/CandlestickChart.tsx";
import * as $$3 from "./islands/DeleteTradeButton.tsx";
import * as $$4 from "./islands/ImportProcessor.tsx";
import * as $$5 from "./islands/Modal.tsx";
import * as $$6 from "./islands/RichEditor.tsx";
import * as $$7 from "./islands/SideMenu.tsx";
import * as $$8 from "./islands/Toast.tsx";
import * as $$9 from "./islands/TradeLogTable.tsx";
import * as $$10 from "./islands/chart.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/ai-coach.ts": $2,
    "./routes/api/export.ts": $3,
    "./routes/api/import-backup.ts": $4,
    "./routes/api/klines.ts": $5,
    "./routes/api/trades.ts": $6,
    "./routes/import_trades.tsx": $7,
    "./routes/index.tsx": $8,
    "./routes/notebook.tsx": $9,
    "./routes/playbook.tsx": $10,
    "./routes/settings.tsx": $11,
    "./routes/stats_daily.tsx": $12,
    "./routes/trade/[tradeID].tsx": $13,
    "./routes/trade_log.tsx": $14,
  },
  islands: {
    "./islands/AICoachButton.tsx": $$0,
    "./islands/AddTradeForm.tsx": $$1,
    "./islands/CandlestickChart.tsx": $$2,
    "./islands/DeleteTradeButton.tsx": $$3,
    "./islands/ImportProcessor.tsx": $$4,
    "./islands/Modal.tsx": $$5,
    "./islands/RichEditor.tsx": $$6,
    "./islands/SideMenu.tsx": $$7,
    "./islands/Toast.tsx": $$8,
    "./islands/TradeLogTable.tsx": $$9,
    "./islands/chart.tsx": $$10,
  },
  baseUrl: import.meta.url,
};

export default manifest;
